### ISSUE TITLE
User Story: Site Navigation

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#1]
As a **User**, I can intuitively navigate through the application so that I can easily find desired content

**Acceptance Criteria:**
1. A navigation bar links to all application pages.
2. Site navigation is responsive adhering to good UI design priciples
3. Navigation restrictions and changes are applied depending on user auth.

**Tasks**
- [ ] Create a styled navbar
- [ ] Ensure the navbar is resposive
- [ ] Distinguish navbar between authenticated users
- [ ] Keep theme of overall website

**Comment by Shane-Donlon** [comment]
Implemented as planned
