### ISSUE TITLE
Unauthenticated Page / landing page

### ISSUE THREAD

**Issue by Shane-Donlon** [DarrachBarneveld/Lepre-Track#15]
This will act as the Home page for the user.
When someone is not authenticated they should be able to access some "about" information etc. that describes the website

As a **User**, I can intuitively understand the reason for the site to exist.

**Acceptance Criteria:**
1. Extends template.html
2. 

**Tasks**
To be added.. the below are template tasks
- [ ] Create a styled navbar
- [ ] Ensure the navbar is resposive
- [ ] Distinguish navbar between authenticated users
- [ ] Keep theme of overall website

**Comment by Shane-Donlon** [comment]
Implemented as planned
