### ISSUE TITLE
User Story: Transport Category

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#16]
As a **User**, I can navigate to a transport page so that I can edit and view my transport score

**Acceptance Criteria:**
1. Users can navigate to the transport category
2. Users can see their transport score
3. Users can edit their metrics to increase/decrease score
4. Users see a slightly more in-depth dashboard specific to transport

**Tasks**
- [ ] Ensure navigation to the transport page via homepage/nav
- [ ] Display user data in a clean and effective dashboard
- [ ] Ensure is fully responsive
- [ ] Create all CRUD request, ie create/read/update data 
- [ ] Write a small excerpt/blurb on the benefits on clean transport

**Comment by Shane-Donlon** [comment]
Implemented as planned
