### ISSUE TITLE
User Story: Energy Category

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#17]
As a **User**, I can navigate to a energy page so that I can edit and view my transport score

**Acceptance Criteria:**
1. Users can navigate to the energy category
2. Users can see their energy score
3. Users can edit their metrics to increase/decrease score
4. Users see a slightly more in-depth dashboard specific to transport

**Tasks**
- [x] Ensure navigation to the energy page via homepage/nav
- [x] Display user data in a clean and effective dashboard
- [x] Ensure is fully responsive
- [x] Create all CRUD request, ie create/read/update data 
- [ ] Write a small excerpt/blurb on the benefits on clean energy

**Comment by Shane-Donlon** [comment]
Implemented as planned
