### ISSUE TITLE
User Story: SignUp

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#2]
As a **User**, I can create an account so that my information is stored for future use.

**Acceptance Criteria:**
1. Users can create an account with an email, password and username
2. Users are authenticated and their data is saved

**Tasks**
- [x] Create A signup form
- [x] Allow users to sign up via email, password, and username
- [x] Create a user document that is linked to the auth
- [ ] Render success and error messages to user
