### ISSUE TITLE
USER STORY: Badge Unlocks

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#20]
As a **User**, I can see which badges I have unlocked so that I can track my progress with goals

**Acceptance Criteria:**
1. A user can see badge unlocks for all necessary categories 
2. Badges are unique from each other  
3. Badges are colourful and descriptive

**Tasks**
- [ ] Create A user badge for 50% green
- [ ] Create A user badge for 75% green
- [ ] Create A user badge for 100% green
- [ ] Create A user badge for energy
- [ ] Create A user badge for diet
- [ ] Create A user badge for transport
- [ ] Create A user badge for community
- [ ] Create a badge cabinet html page for viewing all unlocks

**Comment by Shane-Donlon** [comment]
Implemented as planned
