### ISSUE TITLE
User Story: Landing Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#21]
As a **User**, I can view a landing page so I can see what the site is all about

**Acceptance Criteria:**
1. A landing page based on Shanes dribble
2. Link to registration page
3. Follow the theme of the page

**Tasks**
- [ ] Create a colour scheme - white and green
- [ ] Create A index.html
- [ ] Link to registration page
- [ ] Show basic calculator model 
- [ ] Write blurb or copy of our app

**Comment by Shane-Donlon** [comment]
Implemented as planned
