### ISSUE TITLE
User Story: About US

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#28]
As a **User**, I can find information on the developers so that I can get in touch or view their other work

**Acceptance Criteria:**
1. A user can navigate to an about us/contact us section
2. A user can see each developers information and social links
3. A user gets a brief description of each developer

**Tasks**
- [ ] Create an about us or contact us html page
- [ ] Great a UI design consistent with the current theme
- [ ] List each developer, their name, picture(with consent) a brief excerpt
- [ ] Link linkedin profiles and github profiles of each

**Comment by Shane-Donlon** [comment]
Implemented as planned
