### ISSUE TITLE
User Story: Login

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#3]
As a **User**, I can log into my account so that I can retrieve my data

**Acceptance Criteria:**
1. A user can log into there account
2. Upon logging in their data is retrieved

**Tasks**
- [x] Create a login form
- [x] Upon submission create validation of the user
- [x] If validated retrieve user data
- [x] If invalid render error UI to user
