### ISSUE TITLE
User Story: Home Dashboard

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#4]
As a **User**, I can see all my data and statistics rendered to a home dashboard so that I can keep track of my progress

**Acceptance Criteria:**
1. A user dashboard is viewable upon login
2. The dashboard renders user data into graphs and charts
3. UI principles are adhered to with mobile first development
4. Users can see their overall green rating score
5. Users can see their individual rating score for each category

**Tasks**
- [ ] Create responsive layout for a user dashboard
- [ ] Create graphs and charts that display data in a clean format
- [ ] Allow interaction with charts and graphs based on inputs (ie date)
- [ ] Create an overall score rating
- [ ] Create individual score ratings

**Comment by Shane-Donlon** [comment]
Implemented as planned
